INSERT INTO books VALUES
(01, 01, 'Genesis', 'Gen', 'Ge', NOW(), NOW()),
(02, 02, 'Exodus', 'Ex', 'Exod', NOW(), NOW()),
(03, 03, 'Leviticus', 'Lev', 'Le', NOW(), NOW()),
(04, 04, 'Numbers', 'Num', 'Nu', NOW(), NOW()),
(05, 05, 'Deuteronomy', 'Deut', 'De', NOW(), NOW()),
(06, 06, 'Joshua', 'Josh', 'Jos', NOW(), NOW()),
(07, 07, 'Judges', 'Judg', 'Jdg', NOW(), NOW()),
(08, 08, 'Ruth', 'Ruth', 'Rth', NOW(), NOW()),
(09, 09, '1 Samuel', '1 Sam', '1Sm', NOW(), NOW()),
(10, 10, '2 Samuel', '2 Sam', '2Sm', NOW(), NOW()),
(11, 11, '1 Kings', '1 Kings', '1Kgs', NOW(), NOW()),
(12, 12, '2 Kings', '2 Kings', '2Kgs', NOW(), NOW()),
(13, 13, '1 Chronicles', '1 Chron', '1Chr', NOW(), NOW()),
(14, 14, '2 Chronicles', '2 Chron', '2Chr', NOW(), NOW()),
(15, 15, 'Ezra', 'Ezra', 'Ezr', NOW(), NOW()),
(16, 16, 'Nehemiah', 'Neh', 'Ne', NOW(), NOW()),
(17, 17, 'Esther', 'Est', 'Esth', NOW(), NOW()),
(18, 18, 'Job', 'Job', 'Jb', NOW(), NOW()),
(19, 19, 'Psalms', 'Ps', 'Psalm', NOW(), NOW()),
(20, 20, 'Proverbs', 'Prov', 'Pro', NOW(), NOW()),
(21, 21, 'Ecclesiastes', 'Eccles', 'Eccle', NOW(), NOW()),
(22, 22, 'Song of Solomon', 'Song', 'So', NOW(), NOW()),
(23, 23, 'Isaiah', 'Isa', 'Is', NOW(), NOW()),
(24, 24, 'Jeremiah', 'Jer', 'Je', NOW(), NOW()),
(25, 25, 'Lamentations', 'Lam', 'La', NOW(), NOW()),
(26, 26, 'Ezekiel', 'Ezek', 'Eze', NOW(), NOW()),
(27, 27, 'Daniel', 'Dan', 'Da', NOW(), NOW()),
(28, 28, 'Hosea', 'Hos', 'Ho', NOW(), NOW()),
(29, 29, 'Joel', 'Joel', 'Jl', NOW(), NOW()),
(30, 30, 'Amos', 'Amos', 'Am', NOW(), NOW()),
(31, 31, 'Obadiah', 'Obad', 'Ob', NOW(), NOW()),
(32, 32, 'Jonah', 'Jonah', 'Jnh', NOW(), NOW()),
(33, 33, 'Micah', 'Mic', 'Mc', NOW(), NOW()),
(34, 34, 'Nahum', 'Nah', 'Na', NOW(), NOW()),
(35, 35, 'Habakkuk', 'Hab', 'Hb', NOW(), NOW()),
(36, 36, 'Zephaniah', 'Zeph', 'Zep', NOW(), NOW()),
(37, 37, 'Haggai', 'Hag', 'Hg', NOW(), NOW()),
(38, 38, 'Zechariah', 'Zech', 'Zec', NOW(), NOW()),
(39, 39, 'Malachi', 'Mal', 'Ml', NOW(), NOW()),
(40, 40, 'Matthew', 'Matt', 'Mt', NOW(), NOW()),
(41, 41, 'Mark', 'Mark', 'Mrk', NOW(), NOW()),
(42, 42, 'Luke', 'Luke', 'Luk', NOW(), NOW()),
(43, 43, 'John', 'John', 'Joh', NOW(), NOW()),
(44, 44, 'Acts', 'Acts', 'Act', NOW(), NOW()),
(45, 45, 'Romans', 'Rom', 'Ro', NOW(), NOW()),
(46, 46, '1 Corinthians', '1 Cor', '1Cor', NOW(), NOW()),
(47, 47, '2 Corinthians', '2 Cor', '2Cor', NOW(), NOW()),
(48, 48, 'Galatians', 'Gal', 'Ga', NOW(), NOW()),
(49, 49, 'Ephesians', 'Eph', 'Ephes', NOW(), NOW()),
(50, 50, 'Philippians', 'Phil', 'Php', NOW(), NOW()),
(51, 51, 'Colossians', 'Col', 'Co', NOW(), NOW()),
(52, 52, '1 Thessalonians', '1 Thess', '1Thes', NOW(), NOW()),
(53, 53, '2 Thessalonians', '2 Thess', '2Thes', NOW(), NOW()),
(54, 54, '1 Timothy', '1 Tim', '1Ti', NOW(), NOW()),
(55, 55, '2 Timothy', '2 Tim', '2Ti', NOW(), NOW()),
(56, 56, 'Titus', 'Titus', 'Tit', NOW(), NOW()),
(57, 57, 'Philemon', 'Philem', 'Phm', NOW(), NOW()),
(58, 58, 'Hebrews', 'Heb', 'Heb', NOW(), NOW()),
(59, 59, 'James', 'James', 'Jas', NOW(), NOW()),
(60, 60, '1 Peter', '1 Pet', '1Pt', NOW(), NOW()),
(61, 61, '2 Peter', '2 Pet', '2Pt', NOW(), NOW()),
(62, 62, '1 John', '1 John', '1Jh', NOW(), NOW()),
(63, 63, '2 John', '2 John', '2Jh', NOW(), NOW()),
(64, 64, '3 John', '3 John', '3Jh', NOW(), NOW()),
(65, 65, 'Jude', 'Jude', 'Jud', NOW(), NOW()),
(66, 66, 'Revelation', 'Rev', 'Re', NOW(), NOW());
